{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-gateway.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "postgres-gateway.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "postgres-gateway.name" . }}
    spec:
      serviceAccountName: default
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: pgbouncer
          image: {{ .Values.pgbouncer.image }}
          ports:
            - name: postgresql
              containerPort: 5432
          readinessProbe:
            tcpSocket:
              port: postgresql
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: pgbouncer-config
              mountPath: /etc/pgbouncer/pgbouncer.ini
              subPath: pgbouncer.ini
              readOnly: true
            - name: pgbouncer-users
              mountPath: /etc/pgbouncer/userlist.txt
              subPath: userlist.txt
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: pgbouncer-config
          configMap:
            name: {{ include "postgres-gateway.name" . }}-config
        - name: pgbouncer-users
          secret:
            secretName: {{ include "postgres-gateway.name" . }}-users
{{- end }}
