apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-db
  template:
    metadata:
      labels:
        app: weather-db
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.db.image }}"
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.db.user }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.db.password }}"
        - name: POSTGRES_DB
          value: "{{ .Values.db.name }}"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        {{- if .Values.nfs.enabled }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        {{- end }}
      {{- if .Values.nfs.enabled }}
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: weather-db-pvc
      {{- end }}
