{{- if and .Values.loki.nfs .Values.loki.nfs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: loki-pv
  resources:
    requests:
      storage: {{ .Values.loki.nfs.storage }}
{{- end }}
