{{- if .Values.nfs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tourist-db-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: tourist-db-pv
  resources:
    requests:
      storage: {{ .Values.db.storage }}
{{- end }}
