{{- if .Values.global.nfs.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tourist-db-pv
spec:
  capacity:
    storage: {{ .Values.db.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: {{ .Values.global.nfs.server }}
    path: {{ .Values.global.nfs.basePath }}/tourist-db
{{- end }}
