# gitops/values/eks-b/monitoring-stack-values.yaml
# EKS-B (DR) = 에이전트 (메트릭/로그를 온프레미스 중앙으로 전송)

kube-prometheus-stack:
  enabled: true

  prometheus:
    prometheusSpec:
      externalLabels:
        cluster: eks-b
      remoteWrite:
        - url: "http://172.16.8.32:9090/api/v1/write"

  grafana:
    enabled: false

  alertmanager:
    enabled: false

loki:
  enabled: false

lokiLoadBalancer:
  enabled: false

promtail:
  enabled: true
  config:
    clients:
      - url: "http://172.16.8.34:3100/loki/api/v1/push"
        external_labels:
          cluster: eks-b
    snippets:
      scrapeConfigs: |
        - job_name: jithub-log-only
          static_configs:
            - targets:
                - localhost
              labels:
                job: jithub-log-only
                __path__: /var/log/jithub/*.log

  extraVolumes:
    - name: jithub-logs
      hostPath:
        path: /var/log/jithub
        type: DirectoryOrCreate

  extraVolumeMounts:
    - name: jithub-logs
      mountPath: /var/log/jithub
      readOnly: true
