{{- if .Values.global.nfs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: auth-db-pv
  resources:
    requests:
      storage: {{ .Values.db.storage }}
{{- end }}
