apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: JITHUB_DATABASE_URL
          value: "postgresql://{{ .Values.db.user }}:{{ .Values.db.password }}@auth-db:5432/{{ .Values.db.name }}"
